#lang #lang-c_sharp

# Исключения (Exceptions) в C#

- `Catch` - можно использовать сколько угодно
- Все `catch`-и располагаются в порядке уменьшения конкретики.
- Блок `try` - обязательный, помимо него должен быть еще 1 любой блок (`catch`, `finally`).
- `Finally` выполняется независимо от успеха отлова исключения.
- Если на каком-либо *уровне стека вызовов*, блок `catch` не найден (а найден на верхних уровнях), то для данного уровня, выполнение кода прерывается после выполнения `finally`.
- Компилятор переходит с одного *уровня стека вызовов* на другой - только после завершения выполнения всей `try-catch-finally` конструкции.

```csharp
try
{
   // Код, который может вызвать исключение
}
catch (тип_исключения) // целевой отлов
{
}
catch (тип_исключения имя_переменной) // целевой с возвратом
{
}
catch (...)
{
	 throw;    // можно выполнять повторный выброс исключения
			   // - Полезно для централизованного логирования или обработки исключений.
}
...
catch (Exception ex) // универсальный отлов 1 вар.
{
}
catch // универсальный отлов 2 вар.
{
}
finally
{
   // Код, который будет выполнен в любом случае
   // - Освобождение ресурсов, закрытие файлов или соединений.
}
```

**Содержание базового класса `Exception`:**
- *InnerException*: информация об исключении
- *Message*: текст ошибки
- *Source*: имя объекта или сборки
- *StackTrace*: стек вызывов
- *TargetSite*: упавший метод

###  Throw

Ключевое слово `throw` - позволяет генерировать исключения, как стандартные, так и пользовательские.
Использование одиночного `throw` без указания объекта исключения производится в `catch` для передачи текущего иск. выше по иерархии.

```csharp
// Пример:
throw new Exception("Длина имени меньше 2 символов");
```

### Фильтры исключений

```csharp
catch when(условие) // срабатывает только на true
{
     
}
```

### Пользовательские исключения
Классы, наследуемые от любого стандартного класса исключений (чаще всего базового `Exception`).

```csharp
// Пример:
class PersonException : ArgumentException
{
    public int Value { get;}
    public PersonException(string message, int val)
        : base(message)
    {
        Value = val;
    }
}
```


---
### Примеры

 ```csharp
try
{
	int[] numbers = { 1, 2, 3 };
	Console.WriteLine(numbers[5]); // Вызовет IndexOutOfRangeException
}
catch (IndexOutOfRangeException ex)
{
   Console.WriteLine($"Ошибка: {ex.Message}");
}
finally
{
   Console.WriteLine("Блок finally выполнен.");
}
```

 ```csharp
StreamWriter file = null;
try
{
   file = new StreamWriter("example.txt");
   file.WriteLine("Hello, World!");
}
catch (IOException ex)
{
   Console.WriteLine($"Ошибка ввода-вывода: {ex.Message}");
}
finally
{
   file?.Close();
}
```

 ```csharp
try
{
   try
   {
	   string str = null;
	   int length = str.Length; // Вызовет NullReferenceException
   }
   catch (NullReferenceException ex)
   {
	   Console.WriteLine("Обнаружено исключение NullReferenceException.");
	   throw; // Повторный выброс исключения
   }
}
catch (Exception ex)
{
   Console.WriteLine($"Повторное исключение: {ex.Message}");
}
```